# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :RPM => {
        :box_name => "generic/centos8s",
        :box_version => "4.3.4",
        :cpus => 4,
        :memory => 4096,
        :provision => "./rpm.sh",
    }
}


Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
      config.vm.synced_folder ".", "/vagrant"
      config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.box_version = boxconfig[:box_version]
        box.vm.host_name = boxname.to_s
        box.vm.provision "shell", path: boxconfig[:provision]
        box.vm.provider "virtualbox" do |v|
          v.memory = boxconfig[:memory]
          v.cpus = boxconfig[:cpus]
        end
      end
    end
end
